### ISSUE TITLE
Assets Folder Location

### ISSUE THREAD

**Issue by Zultralord** [DylanDodds/PokeTwitch-Base#1]
When I clone this project and open in it visual studio I get build errors. Dylan, you touched briefly on this in the stream stating that some of the files had to be moved to a debug folder. As I am new to the Visual Studio environment, i'm not sure I know how to best proceed. Can the asset files within the root level assets folder be moved to a more appropriate build location for Visual Studio? I also have an idea that could counter the inconvenience of having these assets moved. We could create a development branch of this project which could be used to facilitate ease of development folder structures (like the one in current use with the Assets folder being located at the root level), this could also help the project house incremental builds. :)

**Comment by OrthoLabs** [comment]
To get the project to work, you have to;

**Comment by OrthoLabs** [comment]
To get the project to work, you have to;
-Download/pull the repo
-Launch Visual Studio (VS 2013+ should work)
-Open the project
-In the Solution Explorer, open references, then Right Click References and select Add References, browse to the project location and go into the assets folder. You need to include the 4 sfmlnet-*.dlls, and the two OpenTK files.
-You should now be able to build the project.
-After you build the project, copy over all the files in the assets folder (not the assets folder itself) over to \src\PokeTwitch.Client\bin\Debug

You should be able to run the project from inside Visual Studio using the 'Run' option now. Feel free to tell me any issues you have, and I can help solve them.

As for future stuff, I'll likely poke Dylan into adding at the very least some automated build scripts, and fixing the broken references.

**Comment by Zultralord** [comment]
Thank you for the assistance in this matter, however I do have som bad news as I am still getting build errors even with the references configured to the specifications you mentioned, I have included a debugging screen shot for documentation purposes. 
![capture](https://cloud.githubusercontent.com/assets/7553521/8156381/4f0a79b4-131a-11e5-9d19-735d8d42ad8d.PNG)

**Comment by OrthoLabs** [comment]
You need to manually copy over the csfml-*.dll files, libsndfile-1.dll, and openal32.dll file next to your .exe

**Comment by OrthoLabs** [comment]
Alternatively, you can download my test branch, which fixes the references problem, and automatically copies all the required assets over to the bin folder automatically. :)

https://github.com/DylanDodds/PokeTwitch-Base/tree/ortho-test-branch

**Comment by Zultralord** [comment]
The issue at this point has been solved thanks to your expertise @OrthoLabs . Had i followed your instructions more precisely, where in which you instructed me to move ALL of the files this issue would have been resolved quicker. Thank you for your help :)

**Comment by OrthoLabs** [comment]
I would appreciate it if you were to pull down my test branch and try that out. If that works for you out of the gate, then I'll push it to Master and then anyone else that tries to build in the future will not have this issue at all.

**Comment by Zultralord** [comment]
As per your request I have pulled down you test branch and can confirm a smooth product run. :) Push away.

**Comment by OrthoLabs** [comment]
Alrighty, great. Thank you very much. :)
